#!/bin/bash

#0.5 breitengrad=1011 px
#-> 1 breitengrad = 2022px
width1=2022
#0.5 höhengrad=1512px
#-> 1 höhengrad=3024px
height1=3024
#height1=3030

#BREITENGRAD
#start=6-596px/2022px
#     =5.705242334322453
startx=5.705242334322453

#HÖHENGRAD
#start=47.5+1159/3024
#     =47.883267195767196
#starty=47.883267195767196
starty=47.9

pin_offset_x=-180
pin_offset_y=-490

getpxwidth(){
	bg_local=$1
	var=$(echo "($bg_local-$startx)*$width1 + $pin_offset_x" | bc )
	printf '%.0f\n' "$var"
}

getpxheight(){
	lg_local=$1
	printf '%.0f\n' "$( echo "($starty-$lg_local)*$height1 + $pin_offset_y" | bc)"
}

rm importer
while read -r line; do
	mountain_name="$(echo "$line" | cut -f1 )"
	mountain_name_adjusted="$(echo "${mountain_name// /_}" | sed 's/\//_/g')"
	hg="$( echo "$line" | cut -f2 )"
	bgg="$( echo "$line" | cut -f3 )"
	printf 'Creating pin for: %s\n' "$mountain_name"
	convert -size 10230x6507 canvas:transparent pin.png -geometry +$(getpxwidth $bgg)+$(getpxheight $hg) -composite temp.png
	convert temp.png -resize 3500x pins/_"${mountain_name_adjusted}.png"
	rm temp.png
	printf "%s\t<img class=imageOverlay src=_%s.png>\n" "$mountain_name" "$mountain_name_adjusted" >> importer
done<coord_file
echo DONE
