#!/bin/bash
pin_offset_x=-180
pin_offset_x=-175
pin_offset_x=-200
#BRUH THIS IS ABSOLUTE TRASH BUT SEEMS TO FIX IT
#pin_offset_y=-490
pin_offset_y=-475
pin_offset_y=-435
#BRUH THIS IS ABSOLUTE TRASH BUT SEEMS TO FIX IT

getpxcoordsy(){
	bg_local=$1
	lg_local=$2
	if [ "$(echo "$bg_local < 8.5" | bc )" -eq 1 ]
	then
		#TOP LEFT
		if [ "$( echo "$lg_local > 46.75" | bc)" -eq 1 ]
		then
			m=-3017.3333333
			b=144470.33333333334
		#BOTTOM LEFT
		elif [ "$( echo "$lg_local < 46.75" | bc)" -eq 1 ]
		then
			m=-3016
			b=144408
		else
			echo "ERROR OUT OF RANGE COORDS"
		fi
	elif [ "$(echo "$bg_local >= 8.5" | bc)" -eq 1 ]
	then
		#TOP RIGHT
		if [ "$( echo "$lg_local > 47" | bc)" -eq 1 ]
		then
			m=-3020
			b=144584
		#BOTTOM RIGHT
		elif [ "$( echo "$lg_local < 47" | bc)" -eq 1 ]
		then
			m=-3017.3333333333333
			b=144459.333333333
			pin_offset_y=-435
			#BRUH THIS IS ABSOLUTE TRASH BUT SEEMS TO FIX IT
		else
			echo "ERROR OUT OF RANGE COORDS"
		fi
	else
		echo "ERROR OUT OF RANGE COORDS"
	fi
	var=$(echo "$m*$lg_local + $b + $pin_offset_y" | bc )
	printf '%.0f\n' "$var"
}

getpxcoordsx(){
	bg_local=$1
	lg_local=$2
	if [ "$(echo "$lg_local > 47" | bc )" -eq 1 ]
	then
		m=2041.5
		b=-11684.25
	elif [ "$(echo "$lg_local <= 47" | bc )" -eq 1 ]
	then
		pin_offset_x=-200
		m=2104.0
		b=-12184
	else
		echo "ERROR OUT OF RANGE COORDS"
	fi
	var=$(echo "$m*$bg_local + $b + $pin_offset_x" | bc )
	printf '%.0f\n' "$var"
}



rm importer
while read -r line; do
	mountain_name="$(echo "$line" | cut -f1 )"
	mountain_name_adjusted="$(echo "${mountain_name// /_}" | sed 's/\//_/g')"
	hg="$( echo "$line" | cut -f2 )"
	bgg="$( echo "$line" | cut -f3 )"
	printf 'Creating pin for: %s\n' "$mountain_name"
	convert -size 10230x6507 canvas:transparent pin.png -geometry +$(getpxcoordsx $bgg $hg)+$(getpxcoordsy $bgg $hg) -composite temp.png
	convert temp.png -resize 3500x pins/_"${mountain_name_adjusted}_map.png"
	rm temp.png
	#mv temp.png ${mountain_name_adjusted}.png
	printf "%s\t<img class=imageOverlay src=_%s_map.png>\n" "$mountain_name" "$mountain_name_adjusted" >> importer
done<coord_file
#echo "stiching..."
#convert -size 10230x6507 canvas:transparent _schweiz_calibration.png -composite LEFT.png -composite RIGHT.png -composite TOP.png -composite BOTTOM.png -composite calibration.png
echo DONE
